// <auto-generated />
using System;
using DemoEF.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DemoEF.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251231084746_UpdateRefreshTokenEntity")]
    partial class UpdateRefreshTokenEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DemoEF.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DemoEF.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@test.com",
                            IsActive = true,
                            Password = "123456",
                            UserName = "admin",
                            UserRole = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "user1@test.com",
                            IsActive = true,
                            Password = "123456",
                            UserName = "user1",
                            UserRole = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "user2@test.com",
                            IsActive = true,
                            Password = "123456",
                            UserName = "user2",
                            UserRole = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "guest1@test.com",
                            IsActive = true,
                            Password = "123456",
                            UserName = "guest1",
                            UserRole = 1
                        },
                        new
                        {
                            Id = 5,
                            Email = "guest2@test.com",
                            IsActive = true,
                            Password = "123456",
                            UserName = "guest2",
                            UserRole = 1
                        },
                        new
                        {
                            Id = 6,
                            Email = "user3@test.com",
                            IsActive = true,
                            Password = "123456",
                            UserName = "user3",
                            UserRole = 2
                        },
                        new
                        {
                            Id = 7,
                            Email = "user4@test.com",
                            IsActive = true,
                            Password = "123456",
                            UserName = "user4",
                            UserRole = 2
                        },
                        new
                        {
                            Id = 8,
                            Email = "user5@test.com",
                            IsActive = true,
                            Password = "123456",
                            UserName = "user5",
                            UserRole = 2
                        },
                        new
                        {
                            Id = 9,
                            Email = "guest3@test.com",
                            IsActive = true,
                            Password = "123456",
                            UserName = "guest3",
                            UserRole = 1
                        },
                        new
                        {
                            Id = 10,
                            Email = "user6@test.com",
                            IsActive = true,
                            Password = "123456",
                            UserName = "user6",
                            UserRole = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
